use std::fs::read_to_string;

use candle_core::{
    Device,
    Tensor,
    DType,
    D
};
use candle_nn::VarBuilder;
use tokenizers::Tokenizer;
use candle_transformers::models::qwen2;
use serde_json::from_str;

pub async fn core(user_input: String) -> String {

    // Collecting words generated by the model:
    let mut answer = String::new();

    let the_path = "/home/mahdi/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-1.5B/snapshots/ad9f0ae0864d7fbcd1cd905e3c6c5b069cc8b562/";

    // Selecting a GPU for model execution and operations:
    let device = match Device::new_cuda(0) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Building a Tokenizer:
    let tokenizer = match Tokenizer::from_file(
        format!("{}tokenizer.json", the_path)
    ) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    /*
        Creating the VarBuilder, 
        which is responsible for delivering the required tensors to the model:
    */
    let var_builder = match unsafe {
        VarBuilder::from_mmaped_safetensors(
            &[format!(
                "{}model.safetensors", 
                the_path
            )], 
            DType::BF16, 
            &device
        )
    } {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Reading the model's config file:
    let tmp = match read_to_string(
        format!(
            "{}config.json", 
            the_path
        )
    ) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Creating a Model Configuration:
    let config: qwen2::Config = match from_str(&tmp) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Model building:
    let mut model = match qwen2::ModelForCausalLM::new(
        &config, 
        var_builder
    ) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    //Formatting user input:
    let prompt = format!(
        "<｜begin▁of▁sentence｜><｜User｜>{}<｜Assistant｜><think>\n",
        user_input
    );

    // Building a token counter:
    let mut generated_tokens = 0;

    // Converting input to numbers:
    let encoding = match tokenizer.encode(
        prompt, 
        false
    ) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Constructing a vector using the generated numbers:
    let mut tokens = encoding.get_ids().to_vec();

    // Creating a Tensor:
    let tensor = match Tensor::new(
        tokens.as_slice(),
        &device
    ) {
        Ok(value) => match value.reshape(
            (1, tokens.as_slice().len())
        ) {
            Ok(reshaped) => reshaped,
            Err(error) => {
                println!("{}", error);
                panic!()
            }
        },
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    println!("encoding: {:?}", encoding.get_tokens());
    println!("tensor: {}", tensor);

    // Clearing Model Memories:
    model.clear_kv_cache();

    // Obtaining the next token ID from the model:
    let logits = match model.forward(
        &tensor, 
        0
    ) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    generated_tokens += 1;

    // Creating a tensor from the token with the highest score:
    let next_token_tensor = match logits
        .squeeze(0)
        .unwrap()
        .squeeze(0)
        .unwrap()
        .argmax(D::Minus1)
    {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Extracting tokens from Tensor:
    let mut next_token_id = match next_token_tensor.to_scalar::<u32>() {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    // Adding the generated token to the vector of tokens:
    tokens.push(next_token_id);

    // Converting a token to a string:
    let decoded = match tokenizer.decode(
        &[next_token_id], 
        false
    ) {
        Ok(value) => value,
        Err(error) => {
            println!("{}", error);
            panic!()
        }
    };

    answer.push_str(&decoded);

    // Repeating the token generation process:
    while next_token_id != 151643 && generated_tokens < 200 {

        let second_tensor = match Tensor::new(
            &[next_token_id], 
            &device
        ) {
            Ok(value) => match value.reshape(
                (1, 1)
            ) {
                Ok(reshaped) => reshaped,
                Err(error) => {
                    println!("{}", error);
                    panic!()
                }
            }
            Err(error) => {
                println!("{}", error);
                panic!()
            }
        };

        let new_logits = match model.forward(
            &second_tensor, 
            tokens.len() - 1
        ) {
            Ok(value) => value,
            Err(error) => {
                println!("{}", error);
                panic!()
            }
        };

        generated_tokens += 1;

        let new_next_token_tensor = match new_logits
            .squeeze(0)
            .unwrap()
            .squeeze(0)
            .unwrap()
            .argmax(D::Minus1)
        {
            Ok(value) => value,
            Err(error) => {
                println!("{}", error);
                panic!()
            }
        };

        next_token_id = match new_next_token_tensor.to_scalar::<u32>() {
            Ok(value) => value,
            Err(error) => {
                println!("{}", error);
                panic!()
            }
        };

        tokens.push(next_token_id);

        let new_decoded = match tokenizer.decode(
            &[next_token_id], 
            false
        ) {
            Ok(value) => value,
            Err(error) => {
                println!("{}", error);
                panic!()
            }
        };

        answer.push_str(&new_decoded);
    }

    answer
}